namespace FolkerKinzel.Contacts.IO.Intls.Csv.Universal;

internal static class ColumnName
{
    internal const string DisplayName = "Display Name";
    internal const string FirstName = "First Name";
    internal const string MiddleName = "Middle Name";
    internal const string LastName = "Last Name";
    internal const string NamePrefix = "Name Prefix";
    internal const string NameSuffix = "Name Suffix";
    internal const string NickName = "Nickname";
    internal const string Gender = "Gender";
    internal const string BirthDay = "Birthday";
    internal const string Spouse = "Spouse";
    internal const string Anniversary = "Anniversary";
    internal const string AddressHomeStreet = "Home Street";
    internal const string AddressHomePostalCode = "Home Postal Code";
    internal const string AddressHomeCity = "Home City";
    internal const string AddressHomeState = "Home State";
    internal const string AddressHomeCountry = "Home Country";
    internal const string Email1 = "E-mail 1";
    internal const string Email2 = "E-mail 2";
    internal const string Email3 = "E-mail 3";
    internal const string Email4 = "E-mail 4";
    internal const string Email5 = "E-mail 5";
    internal const string Email6 = "E-mail 6";
    internal const string PhoneHome = "Phone";
    internal const string PhoneWork = "Work Phone";
    internal const string FaxHome = "Fax";
    internal const string FaxWork = "Work Fax";
    internal const string Cell = "Mobile Phone";
    internal const string CellWork = "Work Mobile Phone";
    internal const string PhoneOther1 = "Other Phone 1";
    internal const string PhoneOther2 = "Other Phone 2";
    internal const string PhoneOther3 = "Other Phone 3";
    internal const string PhoneOther4 = "Other Phone 4";
    internal const string PhoneOther5 = "Other Phone 5";
    internal const string PhoneOther6 = "Other Phone 6";
    internal const string InstantMessenger1 = "Instant Messenger 1";
    internal const string InstantMessenger2 = "Instant Messenger 2";
    internal const string InstantMessenger3 = "Instant Messenger 3";
    internal const string InstantMessenger4 = "Instant Messenger 4";
    internal const string InstantMessenger5 = "Instant Messenger 5";
    internal const string InstantMessenger6 = "Instant Messenger 6";
    internal const string WebPagePersonal = "Web Page";
    internal const string WebPageWork = "Work Web Page";
    internal const string WorkCompany = "Company";
    internal const string WorkDepartment = "Department";
    internal const string WorkOffice = "Office";
    internal const string WorkJobTitle = "Job Title";
    internal const string AddressWorkStreet = "Work Street";
    internal const string AddressWorkPostalCode = "Work Postal Code";
    internal const string AddressWorkCity = "Work City";
    internal const string AddressWorkState = "Work State";
    internal const string AddressWorkCountry = "Work Country";
    internal const string Comment = "Notes";
    internal const string TimeStamp = "Timestamp";
}
