namespace FolkerKinzel.Contacts.IO.Intls.Csv.Google
{
    internal static class HeaderRow
    {
        internal static string[] GetColumnNamesEn() => new string[] {
                "Name",
                "Given Name",
                "Additional Name",
                "Family Name",
                "Yomi Name",
                "Given Name Yomi",
                "Additional Name Yomi",
                "Family Name Yomi",
                "Name Prefix",
                "Name Suffix",
                "Initials",
                "Nickname",
                "Short Name",
                "Maiden Name",
                "Birthday",
                "Gender",
                "Location",
                "Billing Information",
                "Directory Server",
                "Mileage",
                "Occupation",
                "Hobby",
                "Sensitivity",
                "Priority",
                "Subject",
                "Notes",
                "Language",
                "Photo",
                "Group Membership",
                "E-mail 1 - Type",
                "E-mail 1 - Value",
                "E-mail 2 - Type",
                "E-mail 2 - Value",
                "IM 1 - Type",
                "IM 1 - Service",
                "IM 1 - Value",
                "Phone 1 - Type",
                "Phone 1 - Value",
                "Phone 2 - Type",
                "Phone 2 - Value",
                "Phone 3 - Type",
                "Phone 3 - Value",
                "Phone 4 - Type",
                "Phone 4 - Value",
                "Phone 5 - Type",
                "Phone 5 - Value",
                "Phone 6 - Type",
                "Phone 6 - Value",
                "Phone 7 - Type",
                "Phone 7 - Value",
                "Address 1 - Type",
                "Address 1 - Formatted",
                "Address 1 - Street",
                "Address 1 - City",
                "Address 1 - PO Box",
                "Address 1 - Region",
                "Address 1 - Postal Code",
                "Address 1 - Country",
                "Address 1 - Extended Address",
                "Address 2 - Type",
                "Address 2 - Formatted",
                "Address 2 - Street",
                "Address 2 - City",
                "Address 2 - PO Box",
                "Address 2 - Region",
                "Address 2 - Postal Code",
                "Address 2 - Country",
                "Address 2 - Extended Address",
                "Address 3 - Type",
                "Address 3 - Formatted",
                "Address 3 - Street",
                "Address 3 - City",
                "Address 3 - PO Box",
                "Address 3 - Region",
                "Address 3 - Postal Code",
                "Address 3 - Country",
                "Address 3 - Extended Address",
                "Organization 1 - Type",
                "Organization 1 - Name",
                "Organization 1 - Yomi Name",
                "Organization 1 - Title",
                "Organization 1 - Department",
                "Organization 1 - Symbol",
                "Organization 1 - Location",
                "Organization 1 - Job Description",
                "Relation 1 - Type",
                "Relation 1 - Value",
                "Website 1 - Type",
                "Website 1 - Value",
                "Website 2 - Type",
                "Website 2 - Value" };

    }
}
